export default {
  START_TIMER: "START_TIMER",
  RESET_TIMER: "RESET_TIMER",
  TOGGLE_IS_BUSSY_INDICATOR: "TOGGLE_IS_BUSSY_INDICATOR",
  TOGGLE_TIMBER_LABEL: "TOGGLE_TIMER_LABEL",
  ADD_POMODORO: "ADD_POMODORO",
};
